[endpoint]
# Required, IP address to host on, use 127.0.0.1 if you don't know what you're doing.
ip = "127.0.0.1"
# Optional, must be 22024 to work with no client changes
port = 22024

[message]
# The unique id attached to each announcement, the id sent is calculated by '(id * 5) + language'.
# Language can be found in src/lib.rs.

unique_id = 23
# The default message used if any of the messages are empty strings
default_message = '''12/01/2020

Hey crewmates!

Here are some updates for you:
- Fixed the shop menu loading error on Android.
- Christmas cheer is very near! Christmas-themed hats have been added for this month. Thanks for supporting us!
- Server-side bug fixes.

Read all about the v2020.12.1 update [https://sanae6.ca]here[].

Happy Holidays!
'''
# Leave an entry empty (like the first one) to force it to use the default entry
message = ["","Hola Mundo","Olá Mundo","안녕하세요 세상","Привет мир"]