[endpoint]
# Required, IP address to host on, use 127.0.0.1 if you don't know what you're doing.
ip = "127.0.0.1"
# Optional, must be 22024 to work with no client changes
port = 22024

[message]
# The unique id attached to each announcement, the id sent is calculated by '(id * 5) + language'.
# This should be incremented on every announcement change if you are pushing this to users.
# Language can be found in src/lib.rs.
unique_id = 23
# The default message used if any of the messages are empty strings
default_message = '''
This message should be replaced in your config.toml!
'''
# Leave an entry empty (like the first one) to use the default entry
message = ["Hello World","Hola Mundo","Olá Mundo","안녕하세요 세상","Привет мир"]