name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: announce_server
            asset_name: announce-linux-amd64
          - os: windows-latest
            artifact_name: announce_server.exe
            asset_name: announce-windows-amd64
          - os: macos-latest
          artifact_name: announce_server
          asset_name: announce-macos-amd64

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --features="binary" --release --verbose
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: tag-${{ github.ref }}
        overwrite: true
